# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Console
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Random generation
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_ENTROPY_GENERATOR=y

# Memory
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=4096

# Runtime checks
CONFIG_ASSERT=y

# Display
CONFIG_DISPLAY_ANSI_COLORS=y

# QEMU timer configuration
CONFIG_SYS_CLOCK_TICKS_PER_SEC=100
CONFIG_QEMU_ICOUNT=n